services:
    web:
        container_name: repo_apps_web
        build:
            context: .
            dockerfile: Dockerfile.dev.web
        ports:
            - '5173:5173'
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - PORT=5173

    api:
        container_name: repo_apps_api
        build:
            context: .
            dockerfile: Dockerfile.dev.api
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        environment:
            - NODE_ENV=development
            - PORT=3000

    database:
        container_name: repo_services_database
        image: postgres:17.3
        ports:
            - '5433:5432'
        volumes:
            - ./services/database/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=notes

    kvstore:
        container_name: repo_services_kvstore
        image: redis:6.2.5
        ports:
            - '6379:6379'

    dbgate:
        container_name: repo_services_dbgate
        image: dbgate/dbgate:latest
        ports:
            - '3001:3000'
        volumes:
            - ./services/dbgate:/root/.dbgate
        environment:
            - DBGATE_PORT=3000
            - CONNECTIONS=postgres,redis
            - LABEL_postgres=PostgreSQL
            - LABEL_redis=Redis
            - URL_postgres=postgres://postgres:postgres@database:5432
            - URL_redis=redis://kvstore:6379
            - ENGINE_postgres=postgres@dbgate-plugin-postgres
            - ENGINE_redis=redis@dbgate-plugin-redis
